package com.a3groups.bts.services.model.impl;

import com.a3groups.bts.services.model.School;
import com.a3groups.bts.services.service.SchoolLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the School service. Represents a row in the &quot;BTS_School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SchoolImpl}.
 * </p>
 *
 * @author A3 Groups Inc.
 * @see SchoolImpl
 * @see com.a3groups.bts.services.model.School
 * @generated
 */
public abstract class SchoolBaseImpl extends SchoolModelImpl implements School {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a school model instance should use the {@link School} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SchoolLocalServiceUtil.addSchool(this);
        } else {
            SchoolLocalServiceUtil.updateSchool(this);
        }
    }
}
