package com.a3groups.bts.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the School service. Represents a row in the &quot;BTS_School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.a3groups.bts.services.model.impl.SchoolModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.a3groups.bts.services.model.impl.SchoolImpl}.
 * </p>
 *
 * @author A3 Groups Inc.
 * @see School
 * @see com.a3groups.bts.services.model.impl.SchoolImpl
 * @see com.a3groups.bts.services.model.impl.SchoolModelImpl
 * @generated
 */
public interface SchoolModel extends BaseModel<School> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a school model instance should use the {@link School} interface instead.
     */

    /**
     * Returns the primary key of this school.
     *
     * @return the primary key of this school
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this school.
     *
     * @param primaryKey the primary key of this school
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the ID of this school.
     *
     * @return the ID of this school
     */
    public int getId();

    /**
     * Sets the ID of this school.
     *
     * @param id the ID of this school
     */
    public void setId(int id);

    /**
     * Returns the name of this school.
     *
     * @return the name of this school
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this school.
     *
     * @param name the name of this school
     */
    public void setName(String name);

    /**
     * Returns the address of this school.
     *
     * @return the address of this school
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this school.
     *
     * @param address the address of this school
     */
    public void setAddress(String address);

    /**
     * Returns the district of this school.
     *
     * @return the district of this school
     */
    @AutoEscape
    public String getDistrict();

    /**
     * Sets the district of this school.
     *
     * @param district the district of this school
     */
    public void setDistrict(String district);

    /**
     * Returns the city of this school.
     *
     * @return the city of this school
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this school.
     *
     * @param city the city of this school
     */
    public void setCity(String city);

    /**
     * Returns the state of this school.
     *
     * @return the state of this school
     */
    @AutoEscape
    public String getState();

    /**
     * Sets the state of this school.
     *
     * @param state the state of this school
     */
    public void setState(String state);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(School school);

    @Override
    public int hashCode();

    @Override
    public CacheModel<School> toCacheModel();

    @Override
    public School toEscapedModel();

    @Override
    public School toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
